version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: npm install
      # Add tests here if you have them: - run: npm test

  deploy:
    machine:
      image: ubuntu-2204:current 
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS \<< EOF
              rm -rf CA-DevOps
              git clone https://github.com/EskandarAtrakchi/CA-DevOps.git
              cd CA-DevOps
              chmod +x deploy.sh
              ./deploy.sh
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main